name: Deploy Preview to Firebase Hosting

'on':
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HEALTHDESK_2WT04 }}'
          projectId: healthdesk-2wt04
          channelId: pr${{ github.event.pull_request.number }}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HEALTHDESK_2WT04 }}'
          projectId: healthdesk-2wt04
          channelId: pr${{ github.event.pull_request.number }}
          expires: 1s
